config/routes.rb
Rails.application.routes.draw do
  root "questions#index"
  resources :questions, only: %i[new create index show]
  resources :answers, only: :create
  devise_for :users
end

app/models/answer.rb
# frozen_string_literal: true
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :body, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
# frozen_string_literal: true
class Question < ApplicationRecord
  belongs_to :user
  has_many :ordered_answers, -> { order(created_at: :desc) },
           class_name: 'Answer', inverse_of: :question, dependent: :destroy

  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  def name
    email
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(
      user: current_user,
      question_id: answer_params.require(:question_id),
      body: answer_params.fetch(:body)
    )

    if @answer.save
      redirect_to @answer.question, notice: 'Answer was successfully created.'
    else
      redirect_to @answer.question, alert: @answer.errors.full_messages.to_sentence
    end
  end

  private

  def answer_params
    @answer_params ||= params.require(:answer).permit(:body, :question_id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
# frozen_string_literal: true
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc).strict_loading.includes(:user)
  end

  def show
    @question = Question.strict_loading.includes(:user, ordered_answers: :user).find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(user: current_user, body: params.require(:question).fetch(:body))

    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      redirect_to new_question_url, alert: @question.errors.full_messages.to_sentence
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer %>">
  <p class="my-5">
    <%= answer.body %> <span class="text-sm text-slate-400"><%= answer.user.name %> <%= answer.created_at.to_fs(:short) %></span>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this answer", answer, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this answer', edit_answer_path(answer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/answers/_form.html.erb
<%= form_with(model: answer, class: "contents") do |form| %>
  <%= form.hidden_field :question_id, value: answer.question_id %>

  <div class="my-5">
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <p class="my-5">
    <%= question.body %> <span class="text-sm text-slate-400"><%= question.user.name %> <%= question.created_at.to_fs(:short) %></span>


  <% if action_name != "show" %>
    <%= link_to "Show this question", question, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= link_to 'Edit this question', edit_question_path(question), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
  </p>
</div>

app/views/questions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Questions</h1>
    <%= link_to 'New question', new_question_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="questions" class="min-w-full">
    <%= render @questions %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New question</h1>

  <%= render "form", question: @question %>

  <%= link_to 'Back to questions', questions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/questions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <h1 class="text-2xl font-medium">Question</h1>
    <%= render @question %>

    <div class="mt-5">
      <h2 class="text-2xl font-medium">Answers</h2>
      <%= render @question.ordered_answers %>
    </div>

    <div class="mt-5">
      <h2 class="text-2xl font-medium">Add an answer</h2>
      <%= render 'answers/form', answer: Answer.new(question: @question) %>
    </div>
    <%= link_to 'Back to questions', questions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>